### PR TITLE
filter with patient level threshold

### PR DESCRIPTION
**Pull request by mirshahriar**

### CODE REVIEW

**Review by Raajheer1 — DISMISSED** [review]
Why are you rearranging the imports on all these files?

**Comment by mirshahriar** [comment]
> Why are you rearranging the imports on all these files?

This is recommended by Go community. I just ran `goimports` command.

**Comment by Raajheer1** [comment]
> > Why are you rearranging the imports on all these files?
> 
> This is recommended by Go community. I just ran `goimports` command.

They should be from gofmt already

**Comment by mirshahriar** [comment]
> > > Why are you rearranging the imports on all these files?
> > 
> > 
> > This is recommended by Go community. I just ran `goimports` command.
> 
> They should be from gofmt already

`gofmt` only rearranges the orders of the imports.

**Comment by mirshahriar** [comment]
goimport does everything that gofmt do. Additionally it groups and corrects imported packages. While correcting, goimports removes unused imports and adds missing ones. It is so convenient, that most Go programmers prefer goimports to gofmt nowadays.

**Review by weje-air-business — APPROVED** [review]

**Review by weje-air-business — APPROVED** [review]
I'm approving this as we need this for todays client review you guys can later come to some understanding and follow the same standards.

**Pull request merged**
